[platformio]
default_envs = freenove-esp32-s3-wroom

[env:freenove-esp32-s3-wroom]
platform = platformio/espressif32@7.0.1
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.embed_files = data/cert/google-trust-services-roots.pem
extra_scripts = post:merge_firmware.py
build_unflags =
    -std=gnu++11
    -fno-exceptions
build_flags =
    -std=gnu++17
    -fexceptions
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=0
